name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest requests

      - name: Check Directory Structure
        run: ls -R  # Debugging step

      - name: Start FastAPI Server in Background
        run: |
          uvicorn apiserver:app --host 127.0.0.1 --port 8000 > server.log 2>&1 &
          echo "Server is starting..."

      - name: Debug Server Logs
        run: cat server.log || true  # Show server logs if it fails

      - name: Wait for FastAPI to Start
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:8000/docs; then
              echo "✅ FastAPI server is running!"
              exit 0
            fi
            echo "⏳ Waiting for FastAPI..."
            sleep 3
          done
          echo "❌ FastAPI did not start!"
          exit 1  # Fail if the server didn't start

      - name: Run Tests
        run: pytest testautomation2.py --disable-warnings
